/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_robot_et_core_hardware_wakeup_WakeUp */

#ifndef _Included_com_robot_et_core_hardware_wakeup_WakeUp
#define _Included_com_robot_et_core_hardware_wakeup_WakeUp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_robot_et_core_hardware_wakeup_WakeUp
 * Method:    open
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_wakeup_WakeUp_open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_robot_et_core_hardware_wakeup_WakeUp
 * Method:    getWakeUpState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_wakeup_WakeUp_getWakeUpState
  (JNIEnv *, jobject,jint);

/*
 * Class:     com_robot_et_core_hardware_wakeup_WakeUp
 * Method:    getWakeUpDegree
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_wakeup_WakeUp_getWakeUpDegree
  (JNIEnv *, jobject);

/*
 * Class:     com_robot_et_core_hardware_wakeup_WakeUp
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_wakeup_WakeUp_close
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_com_robot_et_core_hardware_wakeup_WakeUp_set_gain_direction
(JNIEnv *, jobject, jint);
#ifdef __cplusplus
}
#endif
#endif
